### ISSUE TITLE
Dapendencies update

### ISSUE THREAD

**Issue by CrisNegoianu** [hoc081098/flutter_google_places_hoc081098#27]
Hi.

Please update the dependencies to the latest version as it's becoming an issue with compatibility with other packages.

Thank you for your work.

**Comment by hoc081098** [comment]
Hi @CrisNegoianu, please try https://pub.dev/packages/flutter_google_places_hoc081098/versions/2.0.0-beta.0. Thanks 🙏

**Comment by CrisNegoianu** [comment]
Thanks for the quick update.
I Really appreciate it.

**Comment by hoc081098** [comment]
> @hoc081098 Please update the package to use updated `google_api_headers: ^4.1.2` 
> This is require to take benefit of [this](https://github.com/fluttercommunity/plus_plugins/issues/2833) security related fixes. 

I will update it ASAP

**Comment by hoc081098** [comment]
https://pub.dev/packages/flutter_google_places_hoc081098/versions/2.0.0 🙏🙏

**Comment by devsideal** [comment]
> https://pub.dev/packages/flutter_google_places_hoc081098/versions/2.0.0 🙏🙏

Thanks a ton @hoc081098

**Comment by devsideal** [comment]
@hoc081098 The latest version `flutter_google_places_hoc081098: ^2.0.0` is still showing the SHA1 security issue, seems its using on another place as well, report showing **Insecure hashing algorithm SHA1 used** with below findings:

![image](https://github.com/hoc081098/flutter_google_places_hoc081098/assets/91250232/d37ccd3f-c6f6-402e-b0f7-117c2f0f5502)

Is there any way to resolve it?
